#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2012 - 2018 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE.md at
## the top level directory of deal.II.
##
## This file is adapted by Sambit Das for use with DFT-FE code
## -------------------------------------------------------------------------------------


source indentationStandard/indent_common.sh

#
# Run sanity checks:
#

checks

#
# Process all source and header files:
#

process "include utils src pseudoConverters" ".*\.(cc|cpp|h|cu|cuh)" format_file

#
# Removing trailing whitespace
#

process "include utils src pseudoConverters" \
  ".*\.(cc|cpp|h|cu|cuh|html|dox|txt)" remove_trailing_whitespace

#
# Ensure only a single newline at end of files
#

process "include utils src pseudoConverters" \
  ".*\.(cc|cpp|h|cu|cuh|html|dox|txt)" ensure_single_trailing_newline

