#!/bin/bash
set -e
set -o pipefail

#script to read paramters file and call the relevant (Release/Debug;Non-Periodic/Periodic) executable 

#
#Usually, no changes are needed to this file
#
validInput=0
if [ $# -eq 3 ]; then
    if [ $1 == "-np" ]; then
	validInput=1
    fi
fi
if [[ $validInput == 1 ]]; then
    echo "reading $3"
else
    # invalid arguments list
    echo "Invalid arguments or incorrect number of arguments passed. Need three arguments. Syntax: ./dftRun -np numProcs parametersFile.prm"
    exit 1             
fi

#check DFT PATH
dftPath=./
while read p; do
    if [[ $p == *"DFT PATH"* ]]; then
	if [[ ${p:0:1} != "#" ]]; then
	    dftPath=`echo "$p" | cut -d'"' -f 2`
	fi
    fi
done < $3
echo "using DFT directory Path: $dftPath"

#check for Optimized/Debug mode and Periodic BC 
optimizedMode=1
periodicBC=0
while read p; do
    #optimized mode
    if [[ $p == *"OPTIMIZED MODE"* ]]; then
	if [[ ${p:0:1} != "#" ]]; then
	    if [[ $p == *"false"* ]]; then
	    optimizedMode=0
	    fi
	fi
    fi
    #periodic BC
    if [[ $p == *"PERIODIC BOUNDARY CONDITION"* ]]; then
        if [[ ${p:0:1} != "#" ]]; then
	    if [[ $p == *"true"* ]]; then
		periodicBC=1
	    fi
	fi
    fi    
done < $3

#call corresponding executable
if [[ $optimizedMode == 1 ]]; then
    if [[ $periodicBC == 1 ]]; then
	execFile="$dftPath/build/release/periodic/main" 
    else
	execFile="$dftPath/build/release/nonPeriodic/main"
    fi
else
   if [[ $periodicBC == 1 ]]; then
       execFile="$dftPath/build/debug/periodic/main"
   else
       execFile="$dftPath/build/debug/nonPeriodic/main"
   fi
fi

#print
if [[ $optimizedMode == 1 ]]; then
    echo "Running in optmized mode"
else
    echo "Running in debug mode"
fi
if [[ $periodicBC == 1 ]]; then
    echo "Periodic BC: true"
else 
    echo "Periodic BC: false"
fi

echo mpirun -np $2 $execFile -p $3
eval mpirun -np $2 $execFile -p $3
