#!/bin/bash
#SBATCH -J SiCdiVacancy
#SBATCH -o SiC.%j.%N.out
#SBATCH -p long
#SBATCH -N 32
#SBATCH -n 1536
#SBATCH -t 96:00:00
##SBATCH --mail-user=phanim@umich.edu
#SBATCH --mail-type=all

echo "Job $SLURM_JOB_NAME, ID $SLURM_JOB_ID"
cd $SLURM_SUBMIT_DIR
ibrun /home1/05363/tg846622/dftfe/build/release/real/main parameterFileAutoMeshGammaPoint.prm>test10.out
