#!/bin/sh
#PBS -A prismsprojectdebug_fluxoe
#PBS -N SI
#PBS -l nodes=2:ppn=16,walltime=03:00:00,pmem=3800mb,qos=flux
#PBS -q fluxoe
#PBS -m abe
#PBS -V
#PBS -M rudraa@umich.edu
echo "I ran on:"
#module unload intel-comp/14.0.2
#module load intel-comp/12.1
module load mkl
#export LD_LIBRARY_PATH=/home/rudraa/software/numerics/petsc-3.3-p6/shared-optimized/lib:$LD_LIBRARY_PATH
# Create a local directory to run and copy your files to local.
# Let PBS handle your output
cd /scratch/prismsproject_fluxoe/rudraa/dft/dft/applications/allElectron/silicon18Atom/

mpirun -np 32 ./main
