var searchData=
[
  ['range',['Range',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structIndexSet_1_1Range.html',1,'IndexSet']]],
  ['readwritevector',['ReadWriteVector',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classLinearAlgebra_1_1ReadWriteVector.html',1,'LinearAlgebra']]],
  ['reductioncontrol',['ReductionControl',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classReductionControl.html',1,'']]],
  ['reductiononsubranges',['ReductionOnSubranges',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structparallel_1_1internal_1_1ReductionOnSubranges.html',1,'parallel::internal']]],
  ['reference',['Reference',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4_1_1Reference.html',1,'SparseMatrixIterators::Accessor&lt; number, false &gt;']]],
  ['reference',['Reference',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classChunkSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4_1_1Reference.html',1,'ChunkSparseMatrixIterators::Accessor&lt; number, false &gt;']]],
  ['referencetype',['ReferenceType',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structTensorAccessors_1_1internal_1_1ReferenceType.html',1,'TensorAccessors::internal']]],
  ['refinementcase',['RefinementCase',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementcase_3c_20g_3a_3adimension_20_3e',['RefinementCase&lt; G::dimension &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementcase_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_201_20_3e_3a_3adimension_20_3e',['RefinementCase&lt; internal::Triangulation::TriaObject&lt; 1 &gt;::dimension &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementcase_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_20dim_20_3e_3a_3adimension_20_3e',['RefinementCase&lt; internal::Triangulation::TriaObject&lt; dim &gt;::dimension &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementcase_3c_20triaobject_3c_202_20_3e_3a_3adimension_20_3e',['RefinementCase&lt; TriaObject&lt; 2 &gt;::dimension &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementcase_3c_20triaobject_3c_203_20_3e_3a_3adimension_20_3e',['RefinementCase&lt; TriaObject&lt; 3 &gt;::dimension &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRefinementCase.html',1,'']]],
  ['refinementdata',['RefinementData',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structTimeStepBase__Tria__Flags_1_1RefinementData.html',1,'TimeStepBase_Tria_Flags']]],
  ['refinementflags',['RefinementFlags',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structTimeStepBase__Tria__Flags_1_1RefinementFlags.html',1,'TimeStepBase_Tria_Flags']]],
  ['refinementpossibilities',['RefinementPossibilities',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structRefinementPossibilities.html',1,'']]],
  ['refinementpossibilities_3c_201_20_3e',['RefinementPossibilities&lt; 1 &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structRefinementPossibilities_3_011_01_4.html',1,'']]],
  ['refinementpossibilities_3c_202_20_3e',['RefinementPossibilities&lt; 2 &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structRefinementPossibilities_3_012_01_4.html',1,'']]],
  ['refinementpossibilities_3c_203_20_3e',['RefinementPossibilities&lt; 3 &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structRefinementPossibilities_3_013_01_4.html',1,'']]],
  ['reinithelper',['ReinitHelper',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20blockvector_3c_20number_20_3e_20_3e',['ReinitHelper&lt; BlockVector&lt; number &gt; &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01BlockVector_3_01number_01_4_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20petscwrappers_3a_3ablockvector_20_3e',['ReinitHelper&lt; PETScWrappers::BlockVector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01PETScWrappers_1_1BlockVector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20petscwrappers_3a_3ampi_3a_3ablockvector_20_3e',['ReinitHelper&lt; PETScWrappers::MPI::BlockVector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01PETScWrappers_1_1MPI_1_1BlockVector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20petscwrappers_3a_3ampi_3a_3avector_20_3e',['ReinitHelper&lt; PETScWrappers::MPI::Vector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01PETScWrappers_1_1MPI_1_1Vector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20petscwrappers_3a_3avector_20_3e',['ReinitHelper&lt; PETScWrappers::Vector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01PETScWrappers_1_1Vector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3ablockvector_20_3e',['ReinitHelper&lt; TrilinosWrappers::BlockVector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01TrilinosWrappers_1_1BlockVector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3ampi_3a_3ablockvector_20_3e',['ReinitHelper&lt; TrilinosWrappers::MPI::BlockVector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01TrilinosWrappers_1_1MPI_1_1BlockVector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3ampi_3a_3avector_20_3e',['ReinitHelper&lt; TrilinosWrappers::MPI::Vector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01TrilinosWrappers_1_1MPI_1_1Vector_01_4.html',1,'internal::LinearOperator']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3avector_20_3e',['ReinitHelper&lt; TrilinosWrappers::Vector &gt;',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classinternal_1_1LinearOperator_1_1ReinitHelper_3_01TrilinosWrappers_1_1Vector_01_4.html',1,'internal::LinearOperator']]],
  ['relaxationblock',['RelaxationBlock',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRelaxationBlock.html',1,'']]],
  ['relaxationblockjacobi',['RelaxationBlockJacobi',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRelaxationBlockJacobi.html',1,'']]],
  ['relaxationblocksor',['RelaxationBlockSOR',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRelaxationBlockSOR.html',1,'']]],
  ['relaxationblockssor',['RelaxationBlockSSOR',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classRelaxationBlockSSOR.html',1,'']]],
  ['residuallocalblockstoglobalblocks',['ResidualLocalBlocksToGlobalBlocks',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classMeshWorker_1_1Assembler_1_1ResidualLocalBlocksToGlobalBlocks.html',1,'MeshWorker::Assembler']]],
  ['residualsimple',['ResidualSimple',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classMeshWorker_1_1Assembler_1_1ResidualSimple.html',1,'MeshWorker::Assembler']]],
  ['returntype',['ReturnType',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structTensorAccessors_1_1ReturnType.html',1,'TensorAccessors']]],
  ['rgbvalues',['RgbValues',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structDataOutBase_1_1EpsFlags_1_1RgbValues.html',1,'DataOutBase::EpsFlags']]],
  ['rowinfo',['RowInfo',['http://www.dealii.org/8.5.0/doxygen/deal.tag/structSparseMatrixEZ_1_1RowInfo.html',1,'SparseMatrixEZ']]],
  ['rungekutta',['RungeKutta',['http://www.dealii.org/8.5.0/doxygen/deal.tag/classTimeStepping_1_1RungeKutta.html',1,'TimeStepping']]]
];
