var searchData=
[
  ['scalar',['Scalar',['structFEValuesExtractors_1_1Scalar.html',1,'FEValuesExtractors']]],
  ['scalar',['Scalar',['structDataPostprocessorInputs_1_1Scalar.html',1,'DataPostprocessorInputs']]],
  ['scalar',['Scalar',['classFEValuesViews_1_1Scalar.html',1,'FEValuesViews']]],
  ['scalarfunctionfromfunctionobject',['ScalarFunctionFromFunctionObject',['classScalarFunctionFromFunctionObject.html',1,'']]],
  ['scaledmatrix',['ScaledMatrix',['classScaledMatrix.html',1,'']]],
  ['schurmatrix',['SchurMatrix',['classSchurMatrix.html',1,'']]],
  ['scope',['Scope',['classTimerOutput_1_1Scope.html',1,'TimerOutput']]],
  ['scopedlock',['ScopedLock',['classThreads_1_1DummyThreadMutex_1_1ScopedLock.html',1,'Threads::DummyThreadMutex']]],
  ['scopedlock',['ScopedLock',['classThreads_1_1Mutex_1_1ScopedLock.html',1,'Threads::Mutex']]],
  ['scratchandcopydataobjects',['ScratchAndCopyDataObjects',['structWorkStream_1_1internal_1_1Implementation3_1_1ScratchAndCopyDataObjects.html',1,'WorkStream::internal::Implementation3']]],
  ['scratchdataobject',['ScratchDataObject',['structWorkStream_1_1internal_1_1Implementation2_1_1IteratorRangeToItemStream_1_1ItemType_1_1ScratchDataObject.html',1,'']]],
  ['secondderivative',['SecondDerivative',['classDerivativeApproximation_1_1internal_1_1SecondDerivative.html',1,'DerivativeApproximation::internal']]],
  ['section',['Section',['structTimerOutput_1_1Section.html',1,'TimerOutput']]],
  ['selection',['Selection',['classPatterns_1_1Selection.html',1,'Patterns']]],
  ['sequential',['Sequential',['classinternal_1_1DoFHandler_1_1Policy_1_1Sequential.html',1,'internal::DoFHandler::Policy']]],
  ['shapefunctiondata',['ShapeFunctionData',['structFEValuesViews_1_1Scalar_1_1ShapeFunctionData.html',1,'FEValuesViews::Scalar']]],
  ['shapefunctiondata',['ShapeFunctionData',['structFEValuesViews_1_1Tensor_3_012_00_01dim_00_01spacedim_01_4_1_1ShapeFunctionData.html',1,'FEValuesViews::Tensor']]],
  ['shapefunctiondata',['ShapeFunctionData',['structFEValuesViews_1_1Vector_1_1ShapeFunctionData.html',1,'FEValuesViews::Vector']]],
  ['shapefunctiondata',['ShapeFunctionData',['structFEValuesViews_1_1SymmetricTensor_3_012_00_01dim_00_01spacedim_01_4_1_1ShapeFunctionData.html',1,'FEValuesViews::SymmetricTensor']]],
  ['shapeinfo',['ShapeInfo',['structinternal_1_1MatrixFreeFunctions_1_1ShapeInfo.html',1,'internal::MatrixFreeFunctions']]],
  ['shift',['Shift',['classPArpackSolver_1_1Shift.html',1,'PArpackSolver']]],
  ['shiftedmatrix',['ShiftedMatrix',['classShiftedMatrix.html',1,'']]],
  ['shiftedmatrixgeneralized',['ShiftedMatrixGeneralized',['classShiftedMatrixGeneralized.html',1,'']]],
  ['signals',['Signals',['structTriangulation_1_1Signals.html',1,'Triangulation']]],
  ['sizeinfo',['SizeInfo',['structinternal_1_1MatrixFreeFunctions_1_1SizeInfo.html',1,'internal::MatrixFreeFunctions']]],
  ['slithypersingularityfunction',['SlitHyperSingularityFunction',['classFunctions_1_1SlitHyperSingularityFunction.html',1,'Functions']]],
  ['slitsingularityfunction',['SlitSingularityFunction',['classFunctions_1_1SlitSingularityFunction.html',1,'Functions']]],
  ['smartpointer',['SmartPointer',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20algorithms_3a_3aoperatorbase_2c_20algorithms_3a_3anewton_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; Algorithms::OperatorBase, Algorithms::Newton&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20algorithms_3a_3aoperatorbase_2c_20algorithms_3a_3athetatimestepping_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; Algorithms::OperatorBase, Algorithms::ThetaTimestepping&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20algorithms_3a_3aoutputoperator_3c_20vectortype_20_3e_2c_20algorithms_3a_3anewton_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; Algorithms::OutputOperator&lt; VectorType &gt;, Algorithms::Newton&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20algorithms_3a_3aoutputoperator_3c_20vectortype_20_3e_2c_20algorithms_3a_3athetatimestepping_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; Algorithms::OutputOperator&lt; VectorType &gt;, Algorithms::ThetaTimestepping&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3adatapostprocessor_3c_20dofhandlertype_3a_3aspace_5fdimension_20_3e_20_3e',['SmartPointer&lt; const ::DataPostprocessor&lt; DoFHandlerType::space_dimension &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_20fevaluestype_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_20fevaluestype_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim, FEValuesType::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim, FEValuesType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FEFaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FEFaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FESubfaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FESubfaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FEValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3afecollection_3c_20dim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::FECollection&lt; dim,::FEValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_20fevaluestype_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_20fevaluestype_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim, FEValuesType::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim, FEValuesType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FEFaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FEFaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FESubfaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FESubfaceValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20fevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FEValues&lt; dim, spacedim &gt;::space_dimension &gt;, FEValuesBase&lt; dim, q_dim,::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20_3a_3ahp_3a_3amappingcollection_3c_20dim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_3a_3aspace_5fdimension_20_3e_2c_20internal_3a_3ahp_3a_3afevaluesbase_3c_20dim_2c_20q_5fdim_2c_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['SmartPointer&lt; const ::hp::MappingCollection&lt; dim,::FEValues&lt; dim, spacedim &gt;::space_dimension &gt;, internal::hp::FEValuesBase&lt; dim, q_dim,::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20additionaldata_2c_20relaxationblock_3c_20matrixtype_2c_20inversenumbertype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const AdditionalData, RelaxationBlock&lt; MatrixType, InverseNumberType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20blockinfo_2c_20meshworker_3a_3aassembler_3a_3amatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; const BlockInfo, MeshWorker::Assembler::MatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20blockinfo_2c_20meshworker_3a_3aassembler_3a_3amgmatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; const BlockInfo, MeshWorker::Assembler::MGMatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20blockinfo_2c_20meshworker_3a_3aassembler_3a_3aresiduallocalblockstoglobalblocks_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const BlockInfo, MeshWorker::Assembler::ResidualLocalBlocksToGlobalBlocks&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20blockinfo_2c_20meshworker_3a_3adofinfo_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const BlockInfo, MeshWorker::DoFInfo&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20blocksparsitypattern_2c_20blocksparsematrix_3c_20number_20_3e_20_3e',['SmartPointer&lt; const BlockSparsityPattern, BlockSparseMatrix&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20chartmanifold_3c_20dim1_2c_20intermediate_5fdim_2c_20chartdim_20_3e_2c_20compositionmanifold_3c_20dim_2c_20spacedim_2c_20chartdim_2c_20dim1_2c_20dim2_2c_20intermediate_5fdim_20_3e_20_3e',['SmartPointer&lt; const ChartManifold&lt; dim1, intermediate_dim, chartdim &gt;, CompositionManifold&lt; dim, spacedim, chartdim, dim1, dim2, intermediate_dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20chartmanifold_3c_20dim2_2c_20spacedim_2c_20intermediate_5fdim_20_3e_2c_20compositionmanifold_3c_20dim_2c_20spacedim_2c_20chartdim_2c_20dim1_2c_20dim2_2c_20intermediate_5fdim_20_3e_20_3e',['SmartPointer&lt; const ChartManifold&lt; dim2, spacedim, intermediate_dim &gt;, CompositionManifold&lt; dim, spacedim, chartdim, dim1, dim2, intermediate_dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20chartmanifold_3c_20dim_5fa_2c_20spacedim_5fa_2c_20chartdim_5fa_20_3e_2c_20tensorproductmanifold_3c_20dim_2c_20dim_5fa_2c_20spacedim_5fa_2c_20chartdim_5fa_2c_20dim_5fb_2c_20spacedim_5fb_2c_20chartdim_5fb_20_3e_20_3e',['SmartPointer&lt; const ChartManifold&lt; dim_A, spacedim_A, chartdim_A &gt;, TensorProductManifold&lt; dim, dim_A, spacedim_A, chartdim_A, dim_B, spacedim_B, chartdim_B &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20chartmanifold_3c_20dim_5fb_2c_20spacedim_5fb_2c_20chartdim_5fb_20_3e_2c_20tensorproductmanifold_3c_20dim_2c_20dim_5fa_2c_20spacedim_5fa_2c_20chartdim_5fa_2c_20dim_5fb_2c_20spacedim_5fb_2c_20chartdim_5fb_20_3e_20_3e',['SmartPointer&lt; const ChartManifold&lt; dim_B, spacedim_B, chartdim_B &gt;, TensorProductManifold&lt; dim, dim_A, spacedim_A, chartdim_A, dim_B, spacedim_B, chartdim_B &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20chunksparsitypattern_2c_20chunksparsematrix_3c_20number_20_3e_20_3e',['SmartPointer&lt; const ChunkSparsityPattern, ChunkSparseMatrix&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20constraintmatrix_20_3e',['SmartPointer&lt; const ConstraintMatrix &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20constraintmatrix_2c_20meshworker_3a_3aassembler_3a_3amatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; const ConstraintMatrix, MeshWorker::Assembler::MatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20constraintmatrix_2c_20meshworker_3a_3aassembler_3a_3amatrixsimple_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; const ConstraintMatrix, MeshWorker::Assembler::MatrixSimple&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20constraintmatrix_2c_20meshworker_3a_3aassembler_3a_3aresiduallocalblockstoglobalblocks_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const ConstraintMatrix, MeshWorker::Assembler::ResidualLocalBlocksToGlobalBlocks&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20constraintmatrix_2c_20meshworker_3a_3aassembler_3a_3aresidualsimple_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const ConstraintMatrix, MeshWorker::Assembler::ResidualSimple&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_20_3e_2c_20pointvaluehistory_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim &gt;, PointValueHistory&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_20_3e_2c_20preconditionmg_3c_20dim_2c_20vectortype_2c_20transfer_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim &gt;, PreconditionMG&lt; dim, VectorType, TRANSFER &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_2c_20spacedim_20_3e_2c_20algorithms_3a_3adofoutputoperator_3c_20vectortype_2c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim, spacedim &gt;, Algorithms::DoFOutputOperator&lt; VectorType, dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_2c_20spacedim_20_3e_2c_20mappingq1eulerian_3c_20dim_2c_20vectortype_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim, spacedim &gt;, MappingQ1Eulerian&lt; dim, VectorType, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandler_3c_20dim_2c_20spacedim_20_3e_2c_20mappingqeulerian_3c_20dim_2c_20vectortype_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const DoFHandler&lt; dim, spacedim &gt;, MappingQEulerian&lt; dim, VectorType, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_20_3e',['SmartPointer&lt; const DoFHandlerType &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_2c_20dataoutstack_3c_20dim_2c_20spacedim_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const DoFHandlerType, DataOutStack&lt; dim, spacedim, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_2c_20functions_3a_3afefieldfunction_3c_20dim_2c_20dofhandlertype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const DoFHandlerType, Functions::FEFieldFunction&lt; dim, DoFHandlerType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_2c_20mappingfefield_3c_20dim_2c_20spacedim_2c_20vectortype_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const DoFHandlerType, MappingFEField&lt; dim, spacedim, VectorType, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_2c_20parallel_3a_3adistributed_3a_3asolutiontransfer_3c_20dim_2c_20vectortype_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const DoFHandlerType, parallel::distributed::SolutionTransfer&lt; dim, VectorType, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20dofhandlertype_2c_20solutiontransfer_3c_20dim_2c_20vectortype_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const DoFHandlerType, SolutionTransfer&lt; dim, VectorType, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20fevaluesbase_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const FEValuesBase&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_203_2c_20spacedim_20_3e_2c_20dofhandler_3c_203_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; 3, spacedim &gt;, DoFHandler&lt; 3, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_20dim_2c_20dim_20_3e_2c_20dofhandler_3c_20dim_2c_20dim_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; dim, dim &gt;, DoFHandler&lt; dim, dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_20dim_2c_20spacedim_20_3e_2c_20dofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; dim, spacedim &gt;, DoFHandler&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_20dim_2c_20spacedim_20_3e_2c_20fevaluesbase_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; dim, spacedim &gt;, FEValuesBase&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_20dim_2c_20spacedim_20_3e_2c_20mappingfefield_3c_20dim_2c_20spacedim_2c_20vectortype_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; dim, spacedim &gt;, MappingFEField&lt; dim, spacedim, VectorType, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20finiteelement_3c_20dim_2c_20spacedim_20_3e_2c_20meshworker_3a_3aintegrationinfo_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const FiniteElement&lt; dim, spacedim &gt;, MeshWorker::IntegrationInfo&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20function_3c_20chartdim_20_3e_2c_20functionmanifold_3c_20dim_2c_20spacedim_2c_20chartdim_20_3e_20_3e',['SmartPointer&lt; const Function&lt; chartdim &gt;, FunctionManifold&lt; dim, spacedim, chartdim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20function_3c_20spacedim_20_3e_2c_20functionmanifold_3c_20dim_2c_20spacedim_2c_20chartdim_20_3e_20_3e',['SmartPointer&lt; const Function&lt; spacedim &gt;, FunctionManifold&lt; dim, spacedim, chartdim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20hp_3a_3adofhandler_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const hp::DoFHandler&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20hp_3a_3afecollection_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const hp::FECollection&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20hp_3a_3ahp_3a_3afecollection_3c_20dim_2c_20dim_20_3e_2c_20hp_3a_3ahp_3a_3adofhandler_3c_20dim_2c_20dim_20_3e_20_3e',['SmartPointer&lt; const hp::hp::FECollection&lt; dim, dim &gt;, hp::hp::DoFHandler&lt; dim, dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20hp_3a_3ahp_3a_3afecollection_3c_20dim_2c_20spacedim_20_3e_2c_20hp_3a_3ahp_3a_3adofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const hp::hp::FECollection&lt; dim, spacedim &gt;, hp::hp::DoFHandler&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20hp_3a_3aqcollection_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const hp::QCollection&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20lapackfullmatrix_3c_20number_20_3e_2c_20preconditionlu_3c_20number_20_3e_20_3e',['SmartPointer&lt; const LAPACKFullMatrix&lt; number &gt;, PreconditionLU&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20ma_5finverse_2c_20schurmatrix_3c_20ma_5finverse_2c_20mb_2c_20mdt_2c_20mc_20_3e_20_3e',['SmartPointer&lt; const MA_inverse, SchurMatrix&lt; MA_inverse, MB, MDt, MC &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20manifold_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Manifold&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20manifold_3c_20dim_2c_20spacedim_20_3e_2c_20triangulation_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Manifold&lt; dim, spacedim &gt;, Triangulation&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mapping_3c_20dim_2c_20spacedim_20_3e_2c_20fevaluesbase_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Mapping&lt; dim, spacedim &gt;, FEValuesBase&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20blockdiagonalmatrix_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, BlockDiagonalMatrix&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20mgcoarsegriditerativesolver_3c_20vectortype_2c_20solvertype_2c_20matrixtype_2c_20preconditionertype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, MGCoarseGridIterativeSolver&lt; VectorType, SolverType, MatrixType, PreconditionerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20pointermatrix_3c_20matrixtype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PointerMatrix&lt; MatrixType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20pointermatrixaux_3c_20matrixtype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PointerMatrixAux&lt; MatrixType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20preconditionblock_3c_20matrixtype_2c_20inverse_5ftype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PreconditionBlock&lt; MatrixType, inverse_type &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20preconditionchebyshev_3c_20matrixtype_2c_20vectortype_2c_20preconditionertype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PreconditionChebyshev&lt; MatrixType, VectorType, PreconditionerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20preconditionrelaxation_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PreconditionRelaxation&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20preconditionselector_3c_20matrixtype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, PreconditionSelector&lt; MatrixType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20relaxationblock_3c_20matrixtype_2c_20inversenumbertype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, RelaxationBlock&lt; MatrixType, InverseNumberType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20shiftedmatrix_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, ShiftedMatrix&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20shiftedmatrixgeneralized_3c_20matrixtype_2c_20matrixtype2_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, ShiftedMatrixGeneralized&lt; MatrixType, MatrixType2, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype_2c_20transposematrix_3c_20matrixtype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType, TransposeMatrix&lt; MatrixType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20matrixtype2_2c_20shiftedmatrixgeneralized_3c_20matrixtype_2c_20matrixtype2_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MatrixType2, ShiftedMatrixGeneralized&lt; MatrixType, MatrixType2, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mb_2c_20schurmatrix_3c_20ma_5finverse_2c_20mb_2c_20mdt_2c_20mc_20_3e_20_3e',['SmartPointer&lt; const MB, SchurMatrix&lt; MA_inverse, MB, MDt, MC &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mc_2c_20schurmatrix_3c_20ma_5finverse_2c_20mb_2c_20mdt_2c_20mc_20_3e_20_3e',['SmartPointer&lt; const MC, SchurMatrix&lt; MA_inverse, MB, MDt, MC &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mdt_2c_20schurmatrix_3c_20ma_5finverse_2c_20mb_2c_20mdt_2c_20mc_20_3e_20_3e',['SmartPointer&lt; const MDt, SchurMatrix&lt; MA_inverse, MB, MDt, MC &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20meshtype_2c_20intergridmap_3c_20meshtype_20_3e_20_3e',['SmartPointer&lt; const MeshType, InterGridMap&lt; MeshType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgcoarsegridbase_3c_20vectortype_20_3e_2c_20multigrid_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGCoarseGridBase&lt; VectorType &gt;, Multigrid&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgconstraineddofs_2c_20meshworker_3a_3aassembler_3a_3amgmatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; const MGConstrainedDoFs, MeshWorker::Assembler::MGMatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgconstraineddofs_2c_20meshworker_3a_3aassembler_3a_3amgmatrixsimple_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; const MGConstrainedDoFs, MeshWorker::Assembler::MGMatrixSimple&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgconstraineddofs_2c_20mglevelglobaltransfer_3c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e_20_3e',['SmartPointer&lt; const MGConstrainedDoFs, MGLevelGlobalTransfer&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgconstraineddofs_2c_20mglevelglobaltransfer_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGConstrainedDoFs, MGLevelGlobalTransfer&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgconstraineddofs_2c_20mgtransferblockbase_20_3e',['SmartPointer&lt; const MGConstrainedDoFs, MGTransferBlockBase &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgmatrixbase_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGMatrixBase&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgmatrixbase_3c_20vectortype_20_3e_2c_20multigrid_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGMatrixBase&lt; VectorType &gt;, Multigrid&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgsmootherbase_3c_20vectortype_20_3e_2c_20mgcoarsegridapplysmoother_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGSmootherBase&lt; VectorType &gt;, MGCoarseGridApplySmoother&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgsmootherbase_3c_20vectortype_20_3e_2c_20multigrid_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGSmootherBase&lt; VectorType &gt;, Multigrid&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20mgtransferbase_3c_20vectortype_20_3e_2c_20multigrid_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const MGTransferBase&lt; VectorType &gt;, Multigrid&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20operatortype_20_3e',['SmartPointer&lt; const OperatorType &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20preconditionertype_2c_20mgcoarsegriditerativesolver_3c_20vectortype_2c_20solvertype_2c_20matrixtype_2c_20preconditionertype_20_3e_20_3e',['SmartPointer&lt; const PreconditionerType, MGCoarseGridIterativeSolver&lt; VectorType, SolverType, MatrixType, PreconditionerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20relaxationblock_3a_3aadditionaldata_2c_20relaxationblock_3c_20matrixtype_2c_20inversenumbertype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; const RelaxationBlock::AdditionalData, RelaxationBlock&lt; MatrixType, InverseNumberType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20sparsematrix_2c_20productsparsematrix_3c_20number_2c_20vector_5fnumber_20_3e_20_3e',['SmartPointer&lt; const SparseMatrix, ProductSparseMatrix&lt; number, vector_number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20sparsematrix_3c_20number_20_3e_2c_20sparsevanka_3c_20number_20_3e_20_3e',['SmartPointer&lt; const SparseMatrix&lt; number &gt;, SparseVanka&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20sparsitypattern_2c_20sparsematrix_3c_20number_20_3e_20_3e',['SmartPointer&lt; const SparsityPattern, SparseMatrix&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20transfer_2c_20preconditionmg_3c_20dim_2c_20vectortype_2c_20transfer_20_3e_20_3e',['SmartPointer&lt; const TRANSFER, PreconditionMG&lt; dim, VectorType, TRANSFER &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_203_2c_20spacedim_20_3e_2c_20dofhandler_3c_203_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; 3, spacedim &gt;, DoFHandler&lt; 3, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20dim_20_3e_2c_20dofhandler_3c_20dim_2c_20dim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, dim &gt;, DoFHandler&lt; dim, dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20dim_20_3e_2c_20hp_3a_3adofhandler_3c_20dim_2c_20dim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, dim &gt;, hp::DoFHandler&lt; dim, dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20dim_20_3e_2c_20timestepbase_5ftria_3c_20dim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, dim &gt;, TimeStepBase_Tria&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20spacedim_20_3e_2c_20dofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, spacedim &gt;, DoFHandler&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20spacedim_20_3e_2c_20hp_3a_3adofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, spacedim &gt;, hp::DoFHandler&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dim_2c_20spacedim_20_3e_2c_20persistenttriangulation_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; dim, spacedim &gt;, PersistentTriangulation&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dofhandler_3c_20dim_20_3e_3a_3adimension_2c_20dofhandler_3c_20dim_20_3e_3a_3aspace_5fdimension_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; DoFHandler&lt; dim &gt;::dimension, DoFHandler&lt; dim &gt;::space_dimension &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20triangulation_3c_20dofhandlertype_3a_3adimension_2c_20dofhandlertype_3a_3aspace_5fdimension_20_3e_20_3e',['SmartPointer&lt; const Triangulation&lt; DoFHandlerType::dimension, DoFHandlerType::space_dimension &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20vector_3c_20number_20_3e_2c_20pointermatrixvector_3c_20number_20_3e_20_3e',['SmartPointer&lt; const Vector&lt; number &gt;, PointerMatrixVector&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20vectortype_2c_20mappingfefield_3c_20dim_2c_20spacedim_2c_20vectortype_2c_20dofhandlertype_20_3e_20_3e',['SmartPointer&lt; const VectorType, MappingFEField&lt; dim, spacedim, VectorType, DoFHandlerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20vectortype_2c_20mappingq1eulerian_3c_20dim_2c_20vectortype_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const VectorType, MappingQ1Eulerian&lt; dim, VectorType, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20const_20vectortype_2c_20mappingqeulerian_3c_20dim_2c_20vectortype_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; const VectorType, MappingQEulerian&lt; dim, VectorType, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20fullmatrix_3c_20float_20_3e_2c_20sparsevanka_3c_20number_20_3e_20_3e',['SmartPointer&lt; FullMatrix&lt; float &gt;, SparseVanka&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20logstream_2c_20logstream_3a_3alogstream_3a_3aprefix_20_3e',['SmartPointer&lt; LogStream, LogStream::LogStream::Prefix &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20matrixblockvector_3c_20matrixtype_20_3e_2c_20meshworker_3a_3aassembler_3a_3amatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; MatrixBlockVector&lt; MatrixType &gt;, MeshWorker::Assembler::MatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20matrixptrvector_2c_20mgmatrixlocalblockstoglobalblocks_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; MatrixPtrVector, MGMatrixLocalBlocksToGlobalBlocks&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20matrixtype_2c_20meshworker_3a_3aassembler_3a_3amatrixsimple_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; MatrixType, MeshWorker::Assembler::MatrixSimple&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20mglevelobject_3c_20matrixtype_20_3e_2c_20meshworker_3a_3aassembler_3a_3amgmatrixsimple_3c_20matrixtype_20_3e_20_3e',['SmartPointer&lt; MGLevelObject&lt; MatrixType &gt;, MeshWorker::Assembler::MGMatrixSimple&lt; MatrixType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20mglevelobject_3c_20matrixtype_20_3e_2c_20mgmatrixselect_3c_20matrixtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; MGLevelObject&lt; MatrixType &gt;, MGMatrixSelect&lt; MatrixType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20multigrid_3c_20vectortype_20_3e_2c_20preconditionmg_3c_20dim_2c_20vectortype_2c_20transfer_20_3e_20_3e',['SmartPointer&lt; Multigrid&lt; VectorType &gt;, PreconditionMG&lt; dim, VectorType, TRANSFER &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20solvercontrol_2c_20solverselector_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; SolverControl, SolverSelector&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20solvertype_2c_20mgcoarsegriditerativesolver_3c_20vectortype_2c_20solvertype_2c_20matrixtype_2c_20preconditionertype_20_3e_20_3e',['SmartPointer&lt; SolverType, MGCoarseGridIterativeSolver&lt; VectorType, SolverType, MatrixType, PreconditionerType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20solvertype_2c_20mgcoarsegridlaciteration_3c_20solvertype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; SolverType, MGCoarseGridLACIteration&lt; SolverType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20timestepbase_2c_20timedependent_20_3e',['SmartPointer&lt; TimeStepBase, TimeDependent &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20triangulation_3c_20dim_2c_20dim_20_3e_2c_20timestepbase_5ftria_3c_20dim_20_3e_20_3e',['SmartPointer&lt; Triangulation&lt; dim, dim &gt;, TimeStepBase_Tria&lt; dim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20triangulation_3c_20dim_2c_20spacedim_20_3e_2c_20gridin_3c_20dim_2c_20spacedim_20_3e_20_3e',['SmartPointer&lt; Triangulation&lt; dim, spacedim &gt;, GridIn&lt; dim, spacedim &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20blockvector_3c_20number_20_3e_20_3e_2c_20mgsmootherblock_3c_20matrixtype_2c_20relaxationtype_2c_20number_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; BlockVector&lt; number &gt; &gt;, MGSmootherBlock&lt; MatrixType, RelaxationType, number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vector_20_3e_2c_20productsparsematrix_3c_20number_2c_20vector_5fnumber_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; Vector &gt;, ProductSparseMatrix&lt; number, vector_number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vector_3c_20number_20_3e_20_3e_2c_20mgtransferblock_3c_20number_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; Vector&lt; number &gt; &gt;, MGTransferBlock&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vector_3c_20number_20_3e_20_3e_2c_20preconditionlu_3c_20number_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; Vector&lt; number &gt; &gt;, PreconditionLU&lt; number &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vectortype_20_3e_2c_20pointermatrixaux_3c_20matrixtype_2c_20vectortype_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; VectorType &gt;, PointerMatrixAux&lt; MatrixType, VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vectortype_20_3e_2c_20productmatrix_3c_20vectortype_20_3e_20_3e',['SmartPointer&lt; VectorMemory&lt; VectorType &gt;, ProductMatrix&lt; VectorType &gt; &gt;',['classSmartPointer.html',1,'']]],
  ['smartpointer_3c_20vectormemory_3c_20vectortype_20_3e_2c_20vectormemory_3a_3apointer_20_3e',['SmartPointer&lt; VectorMemory&lt; VectorType &gt;, VectorMemory::Pointer &gt;',['classSmartPointer.html',1,'']]],
  ['smootherrelaxation',['SmootherRelaxation',['classmg_1_1SmootherRelaxation.html',1,'mg']]],
  ['solutiontransfer',['SolutionTransfer',['classSolutionTransfer.html',1,'']]],
  ['solutiontransfer',['SolutionTransfer',['classparallel_1_1distributed_1_1SolutionTransfer.html',1,'parallel::distributed']]],
  ['solver',['Solver',['classSolver.html',1,'']]],
  ['solverarnoldi',['SolverArnoldi',['classSLEPcWrappers_1_1SolverArnoldi.html',1,'SLEPcWrappers']]],
  ['solverbase',['SolverBase',['classPETScWrappers_1_1SolverBase.html',1,'PETScWrappers']]],
  ['solverbase',['SolverBase',['classSLEPcWrappers_1_1SolverBase.html',1,'SLEPcWrappers']]],
  ['solverbase',['SolverBase',['classTrilinosWrappers_1_1SolverBase.html',1,'TrilinosWrappers']]],
  ['solverbicg',['SolverBiCG',['classPETScWrappers_1_1SolverBiCG.html',1,'PETScWrappers']]],
  ['solverbicgstab',['SolverBicgstab',['classPETScWrappers_1_1SolverBicgstab.html',1,'PETScWrappers']]],
  ['solverbicgstab',['SolverBicgstab',['classTrilinosWrappers_1_1SolverBicgstab.html',1,'TrilinosWrappers']]],
  ['solverbicgstab',['SolverBicgstab',['classSolverBicgstab.html',1,'']]],
  ['solvercg',['SolverCG',['classSolverCG.html',1,'']]],
  ['solvercg',['SolverCG',['classTrilinosWrappers_1_1SolverCG.html',1,'TrilinosWrappers']]],
  ['solvercg',['SolverCG',['classPETScWrappers_1_1SolverCG.html',1,'PETScWrappers']]],
  ['solvercgs',['SolverCGS',['classPETScWrappers_1_1SolverCGS.html',1,'PETScWrappers']]],
  ['solvercgs',['SolverCGS',['classTrilinosWrappers_1_1SolverCGS.html',1,'TrilinosWrappers']]],
  ['solverchebychev',['SolverChebychev',['classPETScWrappers_1_1SolverChebychev.html',1,'PETScWrappers']]],
  ['solvercontrol',['SolverControl',['classSolverControl.html',1,'']]],
  ['solvercr',['SolverCR',['classPETScWrappers_1_1SolverCR.html',1,'PETScWrappers']]],
  ['solverdata',['SolverData',['structPETScWrappers_1_1SolverBase_1_1SolverData.html',1,'PETScWrappers::SolverBase']]],
  ['solverdatamumps',['SolverDataMUMPS',['structPETScWrappers_1_1SparseDirectMUMPS_1_1SolverDataMUMPS.html',1,'PETScWrappers::SparseDirectMUMPS']]],
  ['solverdirect',['SolverDirect',['classTrilinosWrappers_1_1SolverDirect.html',1,'TrilinosWrappers']]],
  ['solverfgmres',['SolverFGMRES',['classSolverFGMRES.html',1,'']]],
  ['solvergeneralizeddavidson',['SolverGeneralizedDavidson',['classSLEPcWrappers_1_1SolverGeneralizedDavidson.html',1,'SLEPcWrappers']]],
  ['solvergmres',['SolverGMRES',['classSolverGMRES.html',1,'']]],
  ['solvergmres',['SolverGMRES',['classPETScWrappers_1_1SolverGMRES.html',1,'PETScWrappers']]],
  ['solvergmres',['SolverGMRES',['classTrilinosWrappers_1_1SolverGMRES.html',1,'TrilinosWrappers']]],
  ['solverjacobidavidson',['SolverJacobiDavidson',['classSLEPcWrappers_1_1SolverJacobiDavidson.html',1,'SLEPcWrappers']]],
  ['solverkrylovschur',['SolverKrylovSchur',['classSLEPcWrappers_1_1SolverKrylovSchur.html',1,'SLEPcWrappers']]],
  ['solverlanczos',['SolverLanczos',['classSLEPcWrappers_1_1SolverLanczos.html',1,'SLEPcWrappers']]],
  ['solverlapack',['SolverLAPACK',['classSLEPcWrappers_1_1SolverLAPACK.html',1,'SLEPcWrappers']]],
  ['solverlsqr',['SolverLSQR',['classPETScWrappers_1_1SolverLSQR.html',1,'PETScWrappers']]],
  ['solverminres',['SolverMinRes',['classSolverMinRes.html',1,'']]],
  ['solverpower',['SolverPower',['classSLEPcWrappers_1_1SolverPower.html',1,'SLEPcWrappers']]],
  ['solverpreonly',['SolverPreOnly',['classPETScWrappers_1_1SolverPreOnly.html',1,'PETScWrappers']]],
  ['solverqmrs',['SolverQMRS',['classSolverQMRS.html',1,'']]],
  ['solverrelaxation',['SolverRelaxation',['classSolverRelaxation.html',1,'']]],
  ['solverrichardson',['SolverRichardson',['classSolverRichardson.html',1,'']]],
  ['solverrichardson',['SolverRichardson',['classPETScWrappers_1_1SolverRichardson.html',1,'PETScWrappers']]],
  ['solverselector',['SolverSelector',['classSolverSelector.html',1,'']]],
  ['solvertcqmr',['SolverTCQMR',['classPETScWrappers_1_1SolverTCQMR.html',1,'PETScWrappers']]],
  ['solvertfqmr',['SolverTFQMR',['classTrilinosWrappers_1_1SolverTFQMR.html',1,'TrilinosWrappers']]],
  ['solvertfqmr',['SolverTFQMR',['classPETScWrappers_1_1SolverTFQMR.html',1,'PETScWrappers']]],
  ['sparseblockvanka',['SparseBlockVanka',['classSparseBlockVanka.html',1,'']]],
  ['sparsedirectmumps',['SparseDirectMUMPS',['classPETScWrappers_1_1SparseDirectMUMPS.html',1,'PETScWrappers']]],
  ['sparsedirectumfpack',['SparseDirectUMFPACK',['classSparseDirectUMFPACK.html',1,'']]],
  ['sparseilu',['SparseILU',['classSparseILU.html',1,'']]],
  ['sparseludecomposition',['SparseLUDecomposition',['classSparseLUDecomposition.html',1,'']]],
  ['sparsematrix',['SparseMatrix',['classPETScWrappers_1_1MPI_1_1SparseMatrix.html',1,'PETScWrappers::MPI']]],
  ['sparsematrix',['SparseMatrix',['classPETScWrappers_1_1SparseMatrix.html',1,'PETScWrappers']]],
  ['sparsematrix',['SparseMatrix',['classSparseMatrix.html',1,'']]],
  ['sparsematrix',['SparseMatrix',['classTrilinosWrappers_1_1SparseMatrix.html',1,'TrilinosWrappers']]],
  ['sparsematrixcollection',['SparseMatrixCollection',['classmg_1_1SparseMatrixCollection.html',1,'mg']]],
  ['sparsematrixez',['SparseMatrixEZ',['classSparseMatrixEZ.html',1,'']]],
  ['sparsemic',['SparseMIC',['classSparseMIC.html',1,'']]],
  ['sparsevanka',['SparseVanka',['classSparseVanka.html',1,'']]],
  ['sparsitypattern',['SparsityPattern',['classTrilinosWrappers_1_1SparsityPattern.html',1,'TrilinosWrappers']]],
  ['sparsitypattern',['SparsityPattern',['classSparsityPattern.html',1,'']]],
  ['spherical',['Spherical',['classFunctions_1_1Spherical.html',1,'Functions']]],
  ['sphericalmanifold',['SphericalManifold',['classSphericalManifold.html',1,'']]],
  ['squarefunction',['SquareFunction',['classFunctions_1_1SquareFunction.html',1,'Functions']]],
  ['standardtensors',['StandardTensors',['classPhysics_1_1Elasticity_1_1StandardTensors.html',1,'Physics::Elasticity']]],
  ['statecombiner',['StateCombiner',['structSolver_1_1StateCombiner.html',1,'Solver']]],
  ['staticmappingq1',['StaticMappingQ1',['structStaticMappingQ1.html',1,'']]],
  ['staticmappingq1',['StaticMappingQ1',['structhp_1_1StaticMappingQ1.html',1,'hp']]],
  ['status',['Status',['structTimeStepping_1_1ImplicitRungeKutta_1_1Status.html',1,'TimeStepping::ImplicitRungeKutta']]],
  ['status',['Status',['structTimeStepping_1_1EmbeddedExplicitRungeKutta_1_1Status.html',1,'TimeStepping::EmbeddedExplicitRungeKutta']]],
  ['status',['Status',['structTimeStepping_1_1TimeStepping_1_1Status.html',1,'TimeStepping::TimeStepping']]],
  ['status',['Status',['structTimeStepping_1_1ExplicitRungeKutta_1_1Status.html',1,'TimeStepping::ExplicitRungeKutta']]],
  ['stokescosine',['StokesCosine',['classFunctions_1_1StokesCosine.html',1,'Functions']]],
  ['stokeslsingularity',['StokesLSingularity',['classFunctions_1_1StokesLSingularity.html',1,'Functions']]],
  ['storagetype',['StorageType',['structinternal_1_1SymmetricTensorAccessors_1_1StorageType.html',1,'internal::SymmetricTensorAccessors']]],
  ['storagetype_3c_202_2c_20dim_2c_20number_20_3e',['StorageType&lt; 2, dim, Number &gt;',['structinternal_1_1SymmetricTensorAccessors_1_1StorageType_3_012_00_01dim_00_01Number_01_4.html',1,'internal::SymmetricTensorAccessors']]],
  ['storagetype_3c_204_2c_20dim_2c_20number_20_3e',['StorageType&lt; 4, dim, Number &gt;',['structinternal_1_1SymmetricTensorAccessors_1_1StorageType_3_014_00_01dim_00_01Number_01_4.html',1,'internal::SymmetricTensorAccessors']]],
  ['straightboundary',['StraightBoundary',['classStraightBoundary.html',1,'']]],
  ['straightboundary_3c_203_2c_20spacedim_20_3e',['StraightBoundary&lt; 3, spacedim &gt;',['classStraightBoundary.html',1,'']]],
  ['straightboundary_3c_20dim_20_3e',['StraightBoundary&lt; dim &gt;',['classStraightBoundary.html',1,'']]],
  ['straightboundary_3c_20dim_2c_20dim_20_3e',['StraightBoundary&lt; dim, dim &gt;',['classStraightBoundary.html',1,'']]],
  ['subcelldata',['SubCellData',['structSubCellData.html',1,'']]],
  ['subdomainequalto',['SubdomainEqualTo',['classIteratorFilters_1_1SubdomainEqualTo.html',1,'IteratorFilters']]],
  ['subfacecase',['SubfaceCase',['classinternal_1_1SubfaceCase.html',1,'internal']]],
  ['subfacepossibilities',['SubfacePossibilities',['structinternal_1_1SubfacePossibilities.html',1,'internal']]],
  ['subfacepossibilities_3c_200_20_3e',['SubfacePossibilities&lt; 0 &gt;',['structinternal_1_1SubfacePossibilities_3_010_01_4.html',1,'internal']]],
  ['subfacepossibilities_3c_201_20_3e',['SubfacePossibilities&lt; 1 &gt;',['structinternal_1_1SubfacePossibilities_3_011_01_4.html',1,'internal']]],
  ['subfacepossibilities_3c_202_20_3e',['SubfacePossibilities&lt; 2 &gt;',['structinternal_1_1SubfacePossibilities_3_012_01_4.html',1,'internal']]],
  ['subfacepossibilities_3c_203_20_3e',['SubfacePossibilities&lt; 3 &gt;',['structinternal_1_1SubfacePossibilities_3_013_01_4.html',1,'internal']]],
  ['subscriptor',['Subscriptor',['classSubscriptor.html',1,'']]],
  ['supportquadrature',['SupportQuadrature',['classMappingQEulerian_1_1MappingQEulerianGeneric_1_1SupportQuadrature.html',1,'MappingQEulerian::MappingQEulerianGeneric']]],
  ['svg',['Svg',['structGridOutFlags_1_1Svg.html',1,'GridOutFlags']]],
  ['svgflags',['SvgFlags',['structDataOutBase_1_1SvgFlags.html',1,'DataOutBase']]],
  ['swappablevector',['SwappableVector',['classSwappableVector.html',1,'']]],
  ['symmetrictensor',['SymmetricTensor',['classSymmetricTensor.html',1,'']]],
  ['symmetrictensor',['SymmetricTensor',['structFEValuesExtractors_1_1SymmetricTensor.html',1,'FEValuesExtractors']]],
  ['symmetrictensor_3c_202_2c_20dim_20_3e',['SymmetricTensor&lt; 2, dim &gt;',['classSymmetricTensor.html',1,'']]],
  ['symmetrictensor_3c_202_2c_20dim_2c_20spacedim_20_3e',['SymmetricTensor&lt; 2, dim, spacedim &gt;',['classFEValuesViews_1_1SymmetricTensor_3_012_00_01dim_00_01spacedim_01_4.html',1,'FEValuesViews']]],
  ['symmetrictensor_3c_202_2c_20spacedim_20_3e',['SymmetricTensor&lt; 2, spacedim &gt;',['classSymmetricTensor.html',1,'']]],
  ['symmetrictensor_3c_204_2c_20dim_20_3e',['SymmetricTensor&lt; 4, dim &gt;',['classSymmetricTensor.html',1,'']]],
  ['synchronousiterators',['SynchronousIterators',['structSynchronousIterators.html',1,'']]],
  ['systemsimple',['SystemSimple',['classMeshWorker_1_1Assembler_1_1SystemSimple.html',1,'MeshWorker::Assembler']]]
];
