var searchData=
[
  ['_40359',['@359',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1@359.html',1,'TrilinosWrappers::internal']]],
  ['_40361',['@361',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@361.html',1,'TrilinosWrappers']]],
  ['_40626',['@626',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@626.html',1,'TrilinosWrappers']]],
  ['_40631',['@631',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@631.html',1,'TrilinosWrappers']]],
  ['_40632',['@632',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@632.html',1,'TrilinosWrappers']]],
  ['_40633',['@633',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1@633.html',1,'TrilinosWrappers::internal']]],
  ['_40634',['@634',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@634.html',1,'TrilinosWrappers']]],
  ['_40634',['@634',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1@634.html',1,'TrilinosWrappers::internal']]],
  ['_40635',['@635',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@635.html',1,'TrilinosWrappers']]],
  ['_40636',['@636',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@636.html',1,'TrilinosWrappers']]],
  ['_40637',['@637',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1@637.html',1,'TrilinosWrappers']]],
  ['blocklinearoperator',['BlockLinearOperator',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1BlockLinearOperator.html',1,'TrilinosWrappers::internal']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceThreads_1_1internal.html',1,'Threads']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal.html',1,'TrilinosWrappers']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTensorAccessors_1_1internal.html',1,'TensorAccessors']]],
  ['internals',['internals',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internals.html',1,'TrilinosWrappers']]],
  ['linearoperator',['LinearOperator',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1LinearOperator.html',1,'TrilinosWrappers::internal']]],
  ['mpi',['MPI',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1MPI.html',1,'TrilinosWrappers']]],
  ['preconditionamg',['PreconditionAMG',['../namespace_trilinos_wrappers_1_1_precondition_a_m_g.html',1,'TrilinosWrappers']]],
  ['preconditionamgmuelu',['PreconditionAMGMueLu',['../namespace_trilinos_wrappers_1_1_precondition_a_m_g_mue_lu.html',1,'TrilinosWrappers']]],
  ['preconditionbase',['PreconditionBase',['../namespace_trilinos_wrappers_1_1_precondition_base.html',1,'TrilinosWrappers']]],
  ['preconditionblockjacobi',['PreconditionBlockJacobi',['../namespace_trilinos_wrappers_1_1_precondition_block_jacobi.html',1,'TrilinosWrappers']]],
  ['preconditionblocksor',['PreconditionBlockSOR',['../namespace_trilinos_wrappers_1_1_precondition_block_s_o_r.html',1,'TrilinosWrappers']]],
  ['preconditionblockssor',['PreconditionBlockSSOR',['../namespace_trilinos_wrappers_1_1_precondition_block_s_s_o_r.html',1,'TrilinosWrappers']]],
  ['preconditionblockwisedirect',['PreconditionBlockwiseDirect',['../namespace_trilinos_wrappers_1_1_precondition_blockwise_direct.html',1,'TrilinosWrappers']]],
  ['preconditionchebyshev',['PreconditionChebyshev',['../namespace_trilinos_wrappers_1_1_precondition_chebyshev.html',1,'TrilinosWrappers']]],
  ['preconditionic',['PreconditionIC',['../namespace_trilinos_wrappers_1_1_precondition_i_c.html',1,'TrilinosWrappers']]],
  ['preconditionidentity',['PreconditionIdentity',['../namespace_trilinos_wrappers_1_1_precondition_identity.html',1,'TrilinosWrappers']]],
  ['preconditionilu',['PreconditionILU',['../namespace_trilinos_wrappers_1_1_precondition_i_l_u.html',1,'TrilinosWrappers']]],
  ['preconditionilut',['PreconditionILUT',['../namespace_trilinos_wrappers_1_1_precondition_i_l_u_t.html',1,'TrilinosWrappers']]],
  ['preconditionjacobi',['PreconditionJacobi',['../namespace_trilinos_wrappers_1_1_precondition_jacobi.html',1,'TrilinosWrappers']]],
  ['preconditionsor',['PreconditionSOR',['../namespace_trilinos_wrappers_1_1_precondition_s_o_r.html',1,'TrilinosWrappers']]],
  ['preconditionssor',['PreconditionSSOR',['../namespace_trilinos_wrappers_1_1_precondition_s_s_o_r.html',1,'TrilinosWrappers']]],
  ['solverbase',['SolverBase',['../namespace_trilinos_wrappers_1_1_solver_base.html',1,'TrilinosWrappers']]],
  ['solverbicgstab',['SolverBicgstab',['../namespace_trilinos_wrappers_1_1_solver_bicgstab.html',1,'TrilinosWrappers']]],
  ['solvercg',['SolverCG',['../namespace_trilinos_wrappers_1_1_solver_c_g.html',1,'TrilinosWrappers']]],
  ['solvercgs',['SolverCGS',['../namespace_trilinos_wrappers_1_1_solver_c_g_s.html',1,'TrilinosWrappers']]],
  ['solverdirect',['SolverDirect',['../namespace_trilinos_wrappers_1_1_solver_direct.html',1,'TrilinosWrappers']]],
  ['solvergmres',['SolverGMRES',['../namespace_trilinos_wrappers_1_1_solver_g_m_r_e_s.html',1,'TrilinosWrappers']]],
  ['solvertfqmr',['SolverTFQMR',['../namespace_trilinos_wrappers_1_1_solver_t_f_q_m_r.html',1,'TrilinosWrappers']]],
  ['sparsematrix',['SparseMatrix',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1internal_1_1SparseMatrix.html',1,'TrilinosWrappers::internal']]],
  ['sparsematrixiterators',['SparseMatrixIterators',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1SparseMatrixIterators.html',1,'TrilinosWrappers']]],
  ['sparsitypatterniterators',['SparsityPatternIterators',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1SparsityPatternIterators.html',1,'TrilinosWrappers']]],
  ['table_3c_202_2c_20smartpointer_3c_20blocktype_2c_20blockmatrixbase_3c_20petscwrappers_3a_3asparsematrix_20_3e_20_3e_20_3e',['Table&lt; 2, SmartPointer&lt; BlockType, BlockMatrixBase&lt; PETScWrappers::SparseMatrix &gt; &gt; &gt;',['../namespace_table_3_012_00_01_smart_pointer_3_01_block_type_00_01_block_matrix_base_3_01_p_e_t_sc_3b5f28b21318b57de64204da8b8d409a.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespace_table_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1_f_e_face_values_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespace_table_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1_f_e_subface_values_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespace_table_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1_f_e_values_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20fevaluestype_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; FEValuesType &gt; &gt;',['../namespace_table_3_013_00_01std__cxx11_1_1shared__ptr_3_01_f_e_values_type_01_4_01_4.html',1,'']]],
  ['table_3c_204_2c_20internal_3a_3amatrixfreefunctions_3a_3ashapeinfo_3c_20number_20_3e_20_3e',['Table&lt; 4, internal::MatrixFreeFunctions::ShapeInfo&lt; Number &gt; &gt;',['../namespace_table_3_014_00_01internal_1_1_matrix_free_functions_1_1_shape_info_3_01_number_01_4_01_4.html',1,'']]],
  ['tablehandler',['TableHandler',['../namespace_table_handler.html',1,'']]],
  ['tensoraccessors',['TensorAccessors',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTensorAccessors.html',1,'']]],
  ['tensorproductpolynomials_3c_20dim_2c_20polynomials_3a_3apiecewisepolynomial_3c_20double_20_3e_20_3e',['TensorProductPolynomials&lt; dim, Polynomials::PiecewisePolynomial&lt; double &gt; &gt;',['../namespace_tensor_product_polynomials_3_01dim_00_01_polynomials_1_1_piecewise_polynomial_3_01double_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3alist_3c_20std_3a_3apair_3c_20bool_2c_20alignedvector_3c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e_20_3e_20_3e',['ThreadLocalStorage&lt; std::list&lt; std::pair&lt; bool, AlignedVector&lt; VectorizedArray&lt; Number &gt; &gt; &gt; &gt; &gt;',['../namespace_thread_local_storage_3_01std_1_1list_3_01std_1_1pair_3_01bool_00_01_aligned_vector_3_0065001d7e7439a43bb85fbefbbc47f6c.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3astack_3c_20std_3a_3astring_20_3e_20_3e',['ThreadLocalStorage&lt; std::stack&lt; std::string &gt; &gt;',['../namespace_thread_local_storage_3_01std_1_1stack_3_01std_1_1string_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3avector_3c_20double_20_3e_20_3e',['ThreadLocalStorage&lt; std::vector&lt; double &gt; &gt;',['../namespace_thread_local_storage_3_01std_1_1vector_3_01double_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3avector_3c_20mu_3a_3aparser_20_3e_20_3e',['ThreadLocalStorage&lt; std::vector&lt; mu::Parser &gt; &gt;',['../namespace_thread_local_storage_3_01std_1_1vector_3_01mu_1_1_parser_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_5fcxx11_3a_3ashared_5fptr_3c_20std_3a_3aostringstream_20_3e_20_3e',['ThreadLocalStorage&lt; std_cxx11::shared_ptr&lt; std::ostringstream &gt; &gt;',['../namespace_thread_local_storage_3_01std__cxx11_1_1shared__ptr_3_01std_1_1ostringstream_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20typename_20dofhandlertype_3a_3aactive_5fcell_5fiterator_20_3e',['ThreadLocalStorage&lt; typename DoFHandlerType::active_cell_iterator &gt;',['../namespace_thread_local_storage_3_01typename_01_do_f_handler_type_1_1active__cell__iterator_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20typename_20workstream_3a_3ainternal_3a_3aimplementation2_3a_3aiteratorrangetoitemstream_3a_3aitemtype_3a_3ascratchdatalist_20_3e',['ThreadLocalStorage&lt; typename WorkStream::internal::Implementation2::IteratorRangeToItemStream::ItemType::ScratchDataList &gt;',['../namespace_thread_local_storage_3_01typename_01_work_stream_1_1internal_1_1_implementation2_1_1_i1456e78da499e9d3881484b23edb024c.html',1,'']]],
  ['threads',['Threads',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceThreads.html',1,'']]],
  ['timeroutput',['TimerOutput',['../namespace_timer_output.html',1,'']]],
  ['timestepbase_5ftria_5fflags',['TimeStepBase_Tria_Flags',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTimeStepBase__Tria__Flags.html',1,'']]],
  ['timestepping',['TimeStepping',['../namespace_time_stepping_1_1_time_stepping.html',1,'TimeStepping']]],
  ['timestepping',['TimeStepping',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTimeStepping.html',1,'']]],
  ['triaaccessorexceptions',['TriaAccessorExceptions',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTriaAccessorExceptions.html',1,'']]],
  ['triangulation',['Triangulation',['../namespace_triangulation.html',1,'']]],
  ['triangulation_3c_20dofhandler_3c_20dim_20_3e_3a_3adimension_2c_20dofhandler_3c_20dim_20_3e_3a_3aspace_5fdimension_20_3e',['Triangulation&lt; DoFHandler&lt; dim &gt;::dimension, DoFHandler&lt; dim &gt;::space_dimension &gt;',['../namespace_triangulation_3_01_do_f_handler_3_01dim_01_4_1_1dimension_00_01_do_f_handler_3_01dim_01_4_1_1space__dimension_01_4.html',1,'']]],
  ['triangulation_3c_20dofhandlertype_3a_3adimension_2c_20dofhandlertype_3a_3aspace_5fdimension_20_3e',['Triangulation&lt; DoFHandlerType::dimension, DoFHandlerType::space_dimension &gt;',['../namespace_triangulation_3_01_do_f_handler_type_1_1dimension_00_01_do_f_handler_type_1_1space__dimension_01_4.html',1,'']]],
  ['triaobjects_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_201_20_3e_20_3e',['TriaObjects&lt; internal::Triangulation::TriaObject&lt; 1 &gt; &gt;',['../namespace_tria_objects_3_01internal_1_1_triangulation_1_1_tria_object_3_011_01_4_01_4.html',1,'']]],
  ['triaobjects_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_20dim_20_3e_20_3e',['TriaObjects&lt; internal::Triangulation::TriaObject&lt; dim &gt; &gt;',['../namespace_tria_objects_3_01internal_1_1_triangulation_1_1_tria_object_3_01dim_01_4_01_4.html',1,'']]],
  ['trilinoswrappers',['TrilinosWrappers',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers.html',1,'']]],
  ['types',['types',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespacetypes.html',1,'']]],
  ['types',['types',['http://www.dealii.org/8.5.0/doxygen/deal.tag/namespaceTrilinosWrappers_1_1types.html',1,'TrilinosWrappers']]]
];
