#!/bin/bash
# Begin LSF Directives
#BSUB -P MAT202
#BSUB -W 0:15
#BSUB -nnodes 1
#BSUB -alloc_flags gpumps
#BSUB -J rundftfe
#BSUB -o rundftfe.%J
#BSUB -e rundftfe.%J
	 
date
jsrun --smpiargs "-gpu" -n 6 -a 1 -c 7 -g 1 -r 6 -d cyclic -b packed:7 ./dftfe parameterFileGPU1.prm > outputGPU1
jsrun --smpiargs "-gpu" -n 6 -a 1 -c 7 -g 1 -r 6 -d cyclic -b packed:7 ./dftfe parameterFileGPU2.prm > outputGPU2
jsrun --smpiargs "-gpu" -n 6 -a 1 -c 7 -g 1 -r 6 -d cyclic -b packed:7 ./dftfe parameterFileGPU3.prm > outputGPU3
jsrun --smpiargs "-gpu" -n 6 -a 1 -c 7 -g 1 -r 6 -d cyclic -b packed:7 ./dftfe parameterFileGPU4.prm > outputGPU4
jsrun --smpiargs "-gpu" -n 6 -a 1 -c 7 -g 1 -r 6 -d cyclic -b packed:7 ./dftfe parameterFileCPU.prm > outputCPU
